server:
  port: 8012

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:xwj_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 123456
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      data-locations: classpath:db/schema.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
